
version: 2
updates:
  # Maintain dependencies for pip
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: monthly
      day: monday
      timezone: Europe/London
    allow:
      # Allow only dependencies in the "Production dependency group"
      - dependency-type: production
    reviewers:
      - ome9ax
    open-pull-requests-limit: 9
